server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location ~* \.csv$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        add_header Pragma "no-cache";
        expires -1;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
